### PR TITLE
fix:Modify usa local json file city name for fix download url append …

### PR DESCRIPTION
**Pull request by mushroom11s**
Fix: modify the city name of the US local JSON file to fix the download URL append error.

### CODE REVIEW

**Comment by treee111** [comment]
Hi @mushroom11s,
thanks for this PR! 👍 

What is the command / UI action causing the tool to break?
I assume the error is because of the URL creation here:
https://github.com/treee111/wahooMapsCreator/blob/26968e5f33338e2aa20246fb98ce56452f54cfb0/wahoomc/downloader.py#L78-L89
We could manage the conversion of `_` to `-` you done in the json-files to be consistent in the `Translate_Country` mapping.
https://github.com/treee111/wahooMapsCreator/blob/26968e5f33338e2aa20246fb98ce56452f54cfb0/wahoomc/constants.py#L24-L31

We might have less changes because each "country" needs only one change and not each occurrence.
Let's see if that would help and is OK for you! :-)

**Comment by treee111** [comment]
OK, I got it.

If I use your branch and call `python -m wahoomc cli -co american_samoa` I still get this error:
image

The mapping of the input to the geofabrik name of the country is needed. As mentioned before this would make the changes of the json files obsolete in my opinion.

I done the change as suggested by me in the comment above.
Could you please checkout if branch `fix-usa_local_json_cityname_error-via-constants` works for you for `american_samoa`.
If you like, you can takeover the changes to your branch and change the other countries in the same way.

Greetings :-)

**Comment by mushroom11s** [comment]
Yes, I got this error when i downloading the map of Massachusetts,and then i found that many cities name are the same

**Comment by mushroom11s** [comment]
All names that contain underlined cities have problems

> Yes, I made this error downloading the map of Massachusetts,and then i found that many cities name are the same

**Comment by treee111** [comment]
Hi @mushroom11s, thanks again for pointing out this `_` to `-` thing!
I implemented the presented solution in #137 
feel free to test it on branch develop :-)

**Pull request closed without merging**
