### PR TITLE
Skip unnecessary processing and other handling of zipping the output

### PR DESCRIPTION
**Pull request by Ebe66**
See title and changelog.

### CODE REVIEW

**Comment by mweirauch** [comment]
Are you sure about the ".v12" suffix. I am pretty sure it should only be ".12" (matching the current version). At least that is what I see on the device and which also makes that tile verification (for map and routing tiles) succeed in the Companion app.

**Comment by treee111** [comment]
wow, this is a massive amount of features and checks implemented. Thanks @Ebe66! 👍

Somewhere, there is a failure under macOS when processing countries throught this branch with all the integrated changes.

I would aim for splitting the changes into several, smaller branches / PR's.
Smaller PR's can be tested & reviewed more straight forward. And when the CHANGELOG gets created automatically in some days in the future, it is also a convenient to have more or less precisely named PR's in place. Hope, this is ok for you!

I extracted changes that belong together into separate PR's:
- https://github.com/treee111/wahooMapsCreator/pull/41
- https://github.com/treee111/wahooMapsCreator/pull/43
- branch `osm-maps-processing-adjustments` for the biggest "hub"
- one or more additional PR's

happy reviewing! ;-)

**Comment by treee111** [comment]
Hi @Ebe66,
thanks for the review of the linked PR's! They are already merged.

Now I have prepared two more, which have most of the functionality and speed-boost I think.
As these are big changes it would be nice if you could have a look if the changes are consistent:  
- https://github.com/treee111/wahooMapsCreator/pull/46
- https://github.com/treee111/wahooMapsCreator/pull/47

After merging these two I compare your branch with develop and look out for changes I didn't catch until then.
Thanks you very much in advance! :-)

**Comment by treee111** [comment]
Hi @Ebe66,
i compared the develop- branch against your branch Ebe66:skip-unnecessary-processing.
The last changes are captured in a last PR which is ready to review:
- #55


After #55 is merged I would close this PR with a big thanks! 👍

**Pull request closed without merging**
