### PR TITLE
[FIX] copy tile-present/version files to map archive

### PR DESCRIPTION
**Pull request by mweirauch**
## This PR…

adds the - currently static numbered - tile-present/version files to the map archival commands.

### CODE REVIEW

**Comment by treee111** [comment]
Hi!
this looks like an enhancement of https://github.com/treee111/wahooMapsCreator/pull/49?
I don't really know for what the .12 files are used. Is it for the newer models ROAM and BOLTv2?

PS: I pushed a commit to delete the (debugging) output. :-)

**Comment by mweirauch** [comment]
Yes, they are used by the BoltApp to check map and routing tile presence. If they are not there it will fail map and routing data validation triggered by the Companion app. At least if they are missing for the routing files, routing is not possible. I think map loading on the device was still fine if the version file was not present. (But my memory is lost on that one.)

In any case, one wants to have these files on both (map and routing tiles), so that the tile checks triggered in the Companion app tell you that everything is alright.

PS: I am gonna force-push again withouth the cmd. Sorry, wasn't paying attention.
PPS: observations on BoltV2 and Companion app

**Comment by mweirauch** [comment]
This seems to be superseeded by #47 from the looks of it. So perhaps just wait for that one and drop this one here then.

**Comment by treee111** [comment]
Sounds good and useful to copy them also in the archive!

You are right, the other PR carries out zipping-changes.
But I think keeping this separate because it is a separate function makes sense, too.

If that is OK for you? You might rebase another time, I'm sorry ;-)

**Comment by mweirauch** [comment]
What I wanted to say is, the other work from Ebe already contains the same functionality if I am not completely mistaken. I'll check when I am back from holidays and report back.

**Comment by treee111** [comment]
Sure, no hurry in here! :)

Concerning the .lzma.12 files I don't something in #47.
In my opinion https://github.com/treee111/wahooMapsCreator/pull/46 creates the .lzma.12 files and this #51 copies them to the archive.
In my head that makes sense but 100% possible that I am mistaken and missed something ;-)

**Comment by treee111** [comment]
You are right, the copy of the files is already included in #47. I totally missed that...

Closing this PR.

**Pull request closed without merging**
